name: Deploy work flow for Amazon ECS

on:
  pull_request:
    branches:
      - main
    types: [closed]

env:
  AWS_REGION: ap-northeast-1
  ECS_LARAVEL_SERVICE: laravel-ecs
  PHP_CONTAINER_NAME: ecs-sample-backend
  NGINX_CONTAINER_NAME: ecs-sample-restapi
  PHP_TAG: latest
  NGINX_TAG: latest
  SLACK_WEBHOOK: https://hooks.slack.com/services/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


jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: php push to ECR
      id: build-image-php
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t $ECR_REGISTRY/$PHP_CONTAINER_NAME:$PHP_TAG .
        docker tag $ECR_REGISTRY/$PHP_CONTAINER_NAME:$PHP_TAG $ECR_REGISTRY/$PHP_CONTAINER_NAME:latest
        docker push $ECR_REGISTRY/$PHP_CONTAINER_NAME:$PHP_TAG
        docker push $ECR_REGISTRY/$PHP_CONTAINER_NAME:latest

    - name: nginx push to ECR
      id: build-image-nginx
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t $ECR_REGISTRY/$NGINX_CONTAINER_NAME:$NGINX_TAG .
        docker tag $ECR_REGISTRY/$NGINX_CONTAINER_NAME:$NGINX_TAG $ECR_REGISTRY/$NGINX_CONTAINER_NAME:latest
        docker push $ECR_REGISTRY/$NGINX_CONTAINER_NAME:$NGINX_TAG
        docker push $ECR_REGISTRY/$NGINX_CONTAINER_NAME:latest

    - name: Deploy to ECS
      run: |
        aws ecs update-service --service $ECS_LARAVEL_SERVICE --cluster ecs-lesson-cluster --force-new-deployment

    - name: Success
      uses: rtCamp/action-slack-notify@v2.0.2
      if: success()
      env:
        SLACK_TITLE: Deploy flow / Success
        SLACK_COLOR: good
        SLACK_MESSAGE: Message for success

    - name: Failure
      uses: rtCamp/action-slack-notify@v2.0.2
      if: failure()
      env:
        SLACK_TITLE: Deploy flow / Failure
        SLACK_COLOR: danger
        SLACK_MESSAGE: Message for failure

    - name: Cancel
      uses: rtCamp/action-slack-notify@v2.0.2
      if: cancelled()
      env:
        SLACK_TITLE: Deploy flow / cancel
        SLACK_COLOR: danger
        SLACK_MESSAGE: Message for Cancel
